#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionReservationHotel
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GestionH")]
	public partial class DataClasseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertReservation(Reservation instance);
    partial void UpdateReservation(Reservation instance);
    partial void DeleteReservation(Reservation instance);
    #endregion
		
		public DataClasseDataContext() : 
				base(global::GestionReservationHotel.Properties.Settings.Default.GestionHConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Reservation> Reservations
		{
			get
			{
				return this.GetTable<Reservation>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Reservation")]
	public partial class Reservation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _NomClient;
		
		private string _PrenomClient;
		
		private string _CINClient;
		
		private System.Nullable<int> _numChambre;
		
		private System.Nullable<System.DateTime> _DateReservation;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNomClientChanging(string value);
    partial void OnNomClientChanged();
    partial void OnPrenomClientChanging(string value);
    partial void OnPrenomClientChanged();
    partial void OnCINClientChanging(string value);
    partial void OnCINClientChanged();
    partial void OnnumChambreChanging(System.Nullable<int> value);
    partial void OnnumChambreChanged();
    partial void OnDateReservationChanging(System.Nullable<System.DateTime> value);
    partial void OnDateReservationChanged();
    #endregion
		
		public Reservation()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomClient", DbType="NChar(10)")]
		public string NomClient
		{
			get
			{
				return this._NomClient;
			}
			set
			{
				if ((this._NomClient != value))
				{
					this.OnNomClientChanging(value);
					this.SendPropertyChanging();
					this._NomClient = value;
					this.SendPropertyChanged("NomClient");
					this.OnNomClientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrenomClient", DbType="NChar(10)")]
		public string PrenomClient
		{
			get
			{
				return this._PrenomClient;
			}
			set
			{
				if ((this._PrenomClient != value))
				{
					this.OnPrenomClientChanging(value);
					this.SendPropertyChanging();
					this._PrenomClient = value;
					this.SendPropertyChanged("PrenomClient");
					this.OnPrenomClientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CINClient", DbType="NChar(10)")]
		public string CINClient
		{
			get
			{
				return this._CINClient;
			}
			set
			{
				if ((this._CINClient != value))
				{
					this.OnCINClientChanging(value);
					this.SendPropertyChanging();
					this._CINClient = value;
					this.SendPropertyChanged("CINClient");
					this.OnCINClientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numChambre", DbType="Int")]
		public System.Nullable<int> numChambre
		{
			get
			{
				return this._numChambre;
			}
			set
			{
				if ((this._numChambre != value))
				{
					this.OnnumChambreChanging(value);
					this.SendPropertyChanging();
					this._numChambre = value;
					this.SendPropertyChanged("numChambre");
					this.OnnumChambreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateReservation", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateReservation
		{
			get
			{
				return this._DateReservation;
			}
			set
			{
				if ((this._DateReservation != value))
				{
					this.OnDateReservationChanging(value);
					this.SendPropertyChanging();
					this._DateReservation = value;
					this.SendPropertyChanged("DateReservation");
					this.OnDateReservationChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
